# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.0"
manifest_format = "2.0"
project_hash = "1183d2b92a836d8a81a461b947a228c660817f07"

[[deps.AbstractAlgebra]]
deps = ["LinearAlgebra", "MacroTools", "Preferences", "Random", "RandomExtensions", "SparseArrays"]
git-tree-sha1 = "399e7d3181001ef0c2ac11cd5101c36dcd6840d9"
uuid = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
version = "0.47.6"

    [deps.AbstractAlgebra.extensions]
    TestExt = "Test"

    [deps.AbstractAlgebra.weakdeps]
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
version = "1.1.2"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
version = "1.11.0"

[[deps.BinaryWrappers]]
deps = ["JLLWrappers", "Scratch"]
git-tree-sha1 = "7fea8f658689fa5062b23f4400eda888b7ae2aaa"
uuid = "f01c122e-0ea1-4f85-ad8f-907073ad7a9f"
version = "0.1.3"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "1.1.1+0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"
version = "1.11.0"

[[deps.Downloads]]
deps = ["ArgTools", "FileWatching", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
version = "1.6.0"

[[deps.FLINT_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "OpenBLAS32_jll"]
git-tree-sha1 = "b730e276143ad63360611f64243117d00276b632"
uuid = "e134572f-a0d5-539d-bddf-3cad8db41a82"
version = "301.400.1+0"

[[deps.FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
version = "1.11.0"

[[deps.GAP]]
deps = ["AbstractAlgebra", "Artifacts", "BinaryWrappers", "Downloads", "FileWatching", "GAP_jll", "GAP_lib_jll", "GAP_pkg_ace_jll", "GAP_pkg_anupq_jll", "GAP_pkg_browse_jll", "GAP_pkg_caratinterface_jll", "GAP_pkg_cddinterface_jll", "GAP_pkg_cohomolo_jll", "GAP_pkg_crypting_jll", "GAP_pkg_curlinterface_jll", "GAP_pkg_cvec_jll", "GAP_pkg_datastructures_jll", "GAP_pkg_deepthought_jll", "GAP_pkg_digraphs_jll", "GAP_pkg_edim_jll", "GAP_pkg_ferret_jll", "GAP_pkg_float_jll", "GAP_pkg_fplsa_jll", "GAP_pkg_gauss_jll", "GAP_pkg_guava_jll", "GAP_pkg_io_jll", "GAP_pkg_json_jll", "GAP_pkg_juliainterface_jll", "GAP_pkg_kbmag_jll", "GAP_pkg_normalizinterface_jll", "GAP_pkg_nq_jll", "GAP_pkg_orb_jll", "GAP_pkg_profiling_jll", "GAP_pkg_semigroups_jll", "GAP_pkg_simpcomp_jll", "GAP_pkg_zeromqinterface_jll", "InteractiveUtils", "Libdl", "MacroTools", "Markdown", "REPL", "Random", "SHA", "Scratch", "Singular_jll", "lib4ti2_jll", "nauty_jll"]
git-tree-sha1 = "06eb3acad78954252bcc38c84765593f543cdcd0"
uuid = "c863536a-3901-11e9-33e7-d5cd0df7b904"
version = "0.16.2"

    [deps.GAP.extensions]
    NemoExt = "Nemo"

    [deps.GAP.weakdeps]
    Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"

[[deps.GAP_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Readline_jll", "Zlib_jll"]
git-tree-sha1 = "0cce2b1bc18c45957d5bf775988b4aea588d6ad5"
uuid = "5cd7a574-2c56-5be2-91dc-c8bc375b9ddf"
version = "400.1500.100+1"

[[deps.GAP_lib_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "52fd7d245ea082668858dc9eca85c9c82d4d54ce"
uuid = "de1ad85e-c930-5cd4-919d-ccd3fcafd1a3"
version = "400.1500.100+0"

[[deps.GAP_pkg_ace_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "cdc100d9acdcb88cc645a5e6402ad3de447a0373"
uuid = "6e11effc-327b-571d-98e3-e12b1d1e7421"
version = "501.70000.0+0"

[[deps.GAP_pkg_anupq_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "f374c2da478f063ad6ab09c74f47b6450359a56b"
uuid = "995f5adf-d221-5ddc-a873-ce518b8081c9"
version = "301.30200.0+0"

[[deps.GAP_pkg_browse_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "4598d8ab6867f0e73442a843220f68f5326f0e29"
uuid = "6e540885-1cbc-538c-85e7-b800ca60d645"
version = "101.82100.0+0"

[[deps.GAP_pkg_caratinterface_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "84e59436473366286551b65d389aaf0e7f9859f6"
uuid = "b60ae38f-62e8-5a18-8dcb-33083e9f01ee"
version = "201.30700.0+0"

[[deps.GAP_pkg_cddinterface_jll]]
deps = ["Artifacts", "GAP_jll", "GMP_jll", "JLLWrappers", "Libdl", "cddlib_jll"]
git-tree-sha1 = "2c16625e5aee6d5ebd814d3d6d78881c357e6c90"
uuid = "edf6cd94-1a94-567d-837e-37d1f3b87eed"
version = "202501.62400.0+0"

[[deps.GAP_pkg_cohomolo_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "90cbb55a50328962e575cdcd60524190308d331d"
uuid = "386407dc-74c0-5367-b2ac-4ae54610b78b"
version = "101.61200.0+0"

[[deps.GAP_pkg_crypting_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "8c5b199301e99db03b67552b06959352f0a83fa2"
uuid = "3b5f52f3-99b5-593a-81cd-d6cf4b425c55"
version = "1.100600.0+0"

[[deps.GAP_pkg_curlinterface_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "LibCURL_jll", "Libdl"]
git-tree-sha1 = "f039e303d81abb44be874a3e93755f7c9a74d6bf"
uuid = "deeb07ae-e8f4-5d6c-9f2a-02b0e630ae3b"
version = "201.40200.0+0"

[[deps.GAP_pkg_cvec_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "208937f4a5c695eea11fac4eb41b0ca64bb982dc"
uuid = "03de9d45-54dd-5e36-9810-6ca1d577e6b3"
version = "201.80400.0+0"

[[deps.GAP_pkg_datastructures_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "56fba05b45826f24442cff50cfa13a485374eaaf"
uuid = "66bcec33-4fa3-551a-b2da-ca256b6829d9"
version = "1.40000.0+0"

[[deps.GAP_pkg_deepthought_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "8dbe0b2a20230417bba46cb1dd76a0704de18f0a"
uuid = "27af9300-c9da-50fb-ba64-a6b0776a3078"
version = "101.900.0+0"

[[deps.GAP_pkg_digraphs_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "b691448c5128696afd18da2e6dcd01c3070e35d5"
uuid = "ce5c30f6-a98c-53bc-b643-089f5717f8db"
version = "101.130100.0+0"

[[deps.GAP_pkg_edim_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "f2f105a7ccf17af37b2c382b248f3f83d4a21d12"
uuid = "aa0ab9cb-918b-5ca1-812e-3cecb1c413b6"
version = "101.30800.0+0"

[[deps.GAP_pkg_ferret_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "15f24d74dbb2d579c4fa4ef87f7a13c5ac39b9ff"
uuid = "d6652ff9-bdf9-5f19-9e6f-c10727807222"
version = "101.1500.0+0"

[[deps.GAP_pkg_float_jll]]
deps = ["Artifacts", "GAP_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPC_jll", "MPFI_jll", "MPFR_jll"]
git-tree-sha1 = "97ebd88c6ed415c3658c2fa7e43a18b2b120a9de"
uuid = "b73cfdca-4c14-50a3-9408-5dcda5b8fad2"
version = "101.900.0+0"

[[deps.GAP_pkg_fplsa_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "6167128163b7e81bdee6b718947a614092a26127"
uuid = "f51f7fb6-0f19-5db2-8aaf-495cce673bcb"
version = "101.20700.0+0"

[[deps.GAP_pkg_gauss_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "9f8518ded1fea55f0687f18e2d6b603e374c63d9"
uuid = "296a3c51-2614-5f89-afa9-2c5cd84b74d9"
version = "202401.110100.0+0"

[[deps.GAP_pkg_guava_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "09ee1f92c3f4074a49f27ddf18670a93f0fcf400"
uuid = "70456840-cd51-5d76-a902-d128bd76a730"
version = "301.200000.0+0"

[[deps.GAP_pkg_io_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "1f0867c8166e6e3f56c7dca7ad792a2fadf66847"
uuid = "19a9678b-966c-568e-9f2e-41ceac70c829"
version = "401.90300.0+0"

[[deps.GAP_pkg_json_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "a17cd0b64ec648b9d31bd0e1e60c4936c19e4e76"
uuid = "b348cf08-4407-5d37-b307-1564396f8b07"
version = "201.20300.0+0"

[[deps.GAP_pkg_juliainterface_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "1061a3cb62bf7b78c247bf64bb86b50bbc21406b"
uuid = "ba154793-3a7d-51ee-8800-e295b0cf7374"
version = "0.160000.0+1"

[[deps.GAP_pkg_kbmag_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "b17c7f39377e49dc755c5a221bb131a4a1bb8af8"
uuid = "74c39be2-f71b-5dd1-bffc-f479ee282a63"
version = "101.51100.0+0"

[[deps.GAP_pkg_normalizinterface_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl", "normaliz_jll"]
git-tree-sha1 = "09ab4246810b3a62a32374d6eb67cc0cf3cff244"
uuid = "74f4ad05-5f81-5a78-8197-4e83b84c9c17"
version = "101.40100.0+0"

[[deps.GAP_pkg_nq_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "85a7f2f82cde66b39d9f2dadc887e05c32ed3d33"
uuid = "00bf61e5-c0f9-5a3f-ba8b-68a621695b53"
version = "201.51100.0+0"

[[deps.GAP_pkg_orb_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "9d2549b3f649406aff9622fca9847786d2a8b3ad"
uuid = "b689cd95-dcfd-544e-a174-ce2fd787c795"
version = "501.100.0+0"

[[deps.GAP_pkg_profiling_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "2667f05f31c2c6f3905c7307f52bc98521756cbb"
uuid = "d3697a66-ac8c-5833-932f-cdd896efbdde"
version = "201.60200.0+0"

[[deps.GAP_pkg_semigroups_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "62f41de88b8cf66af07070f5b8d5d77def067239"
uuid = "6263fdc2-b0d3-58ac-9933-e1550bf6ed81"
version = "501.50400.0+0"

[[deps.GAP_pkg_simpcomp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "29f9b49ac28db778c4199323829432587b7ee476"
uuid = "1c659ad8-f6e2-554d-814b-22ddd907b91c"
version = "201.11400.0+0"

[[deps.GAP_pkg_zeromqinterface_jll]]
deps = ["Artifacts", "GAP_jll", "JLLWrappers", "Libdl", "ZeroMQ_jll"]
git-tree-sha1 = "5692bdf88eae2e876f849809e5820ce6f4b2e36a"
uuid = "abf7faeb-cafb-5034-8851-d0d251ebcfa3"
version = "1.170000.0+0"

[[deps.GLPK_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "6aa6294ba949ccfc380463bf50ff988b46de5bc7"
uuid = "e8aa6df9-e6ca-548a-97ff-1f85fc5b8b98"
version = "5.0.1+1"

[[deps.GMP_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version = "6.3.0+0"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
version = "1.11.0"

[[deps.JLLWrappers]]
deps = ["Artifacts", "Preferences"]
git-tree-sha1 = "0533e564aae234aff59ab625543145446d8b6ec2"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.7.1"

[[deps.LLVMOpenMP_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "eb62a3deb62fc6d8822c0c4bef73e4412419c5d8"
uuid = "1d63c593-3942-5779-bab2-d838dc0a180e"
version = "18.1.8+0"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.6.4"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
version = "8.6.0+0"

[[deps.LibGit2]]
deps = ["Base64", "LibGit2_jll", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"
version = "1.11.0"

[[deps.LibGit2_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll"]
uuid = "e37daf67-58a4-590a-8e99-b0245dd2ffc5"
version = "1.7.2+0"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"
version = "1.11.0+1"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
version = "1.11.0"

[[deps.LinearAlgebra]]
deps = ["Libdl", "OpenBLAS_jll", "libblastrampoline_jll"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
version = "1.11.0"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"
version = "1.11.0"

[[deps.MPC_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll"]
git-tree-sha1 = "214b9b320b80528b95559b1dac8673737d728800"
uuid = "2ce0c516-f11f-5db3-98ad-e0e1048fbd70"
version = "1.3.1+0"

[[deps.MPFI_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll"]
git-tree-sha1 = "250d1a35d37c2c2e0f72429f2bf172d684edff97"
uuid = "e8b5fb6c-218f-5c08-bc3d-6b0e551bbffd"
version = "1.5.6+0"

[[deps.MPFR_jll]]
deps = ["Artifacts", "GMP_jll", "Libdl"]
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"
version = "4.2.1+0"

[[deps.MacroTools]]
git-tree-sha1 = "1e0228a030642014fe5cfe68c2c0a818f9e3f522"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.16"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
version = "1.11.0"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
version = "2.28.6+0"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"
version = "2023.12.12"

[[deps.Ncurses_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "b5e7e7ad16adfe5f68530f9f641955b5b0f12bbb"
uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
version = "6.5.1+0"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
version = "1.2.0"

[[deps.OpenBLAS32_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "ece4587683695fe4c5f20e990da0ed7e83c351e7"
uuid = "656ef2d0-ae68-5445-9ca0-591084a874a2"
version = "0.3.29+0"

[[deps.OpenBLAS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Libdl"]
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"
version = "0.3.27+1"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "FileWatching", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "Random", "SHA", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
version = "1.11.0"
weakdeps = ["REPL"]

    [deps.Pkg.extensions]
    REPLExt = "REPL"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "522f093a29b31a93e34eaea17ba055d850edea28"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.5.1"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "StyledStrings", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
version = "1.11.0"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.RandomExtensions]]
deps = ["Random", "SparseArrays"]
git-tree-sha1 = "b8a399e95663485820000f26b6a43c794e166a49"
uuid = "fb686558-2515-59ef-acaa-46db3789a887"
version = "0.4.4"

[[deps.Readline_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Ncurses_jll"]
git-tree-sha1 = "6044f482a91c7aa2b82ab614aedd726be633ad05"
uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
version = "8.2.13+0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Scratch]]
deps = ["Dates"]
git-tree-sha1 = "9b81b8393e50b7d4e6d0a9f14e192294d3b7c109"
uuid = "6c6a2e73-6563-6170-7368-637461726353"
version = "1.3.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
version = "1.11.0"

[[deps.Singular_jll]]
deps = ["Artifacts", "FLINT_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "cddlib_jll"]
git-tree-sha1 = "8fab3fc7ab4fc38f0e3927af4289f7e8c37c6cdd"
uuid = "43d676ae-4934-50ba-8046-7a96366d613b"
version = "404.101.503+0"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"
version = "1.11.0"

[[deps.SparseArrays]]
deps = ["Libdl", "LinearAlgebra", "Random", "Serialization", "SuiteSparse_jll"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
version = "1.11.0"

[[deps.StyledStrings]]
uuid = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
version = "1.11.0"

[[deps.SuiteSparse_jll]]
deps = ["Artifacts", "Libdl", "libblastrampoline_jll"]
uuid = "bea87d4a-7f5b-5778-9afe-8cc45184846c"
version = "7.7.0+0"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
version = "1.0.3"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
version = "1.10.0"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
version = "1.11.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"

[[deps.ZeroMQ_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "libsodium_jll"]
git-tree-sha1 = "766d90db2817565b667c1cc9cc420d668f2e8dba"
uuid = "8f1865be-045e-5c20-9c9f-bfbfb0764568"
version = "4.3.6+0"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.13+1"

[[deps.cddlib_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "932ceeea3797cd95a1b2e0f978aa33a355f04cbf"
uuid = "f07e07eb-5685-515a-97c8-3014f6152feb"
version = "0.94.15+0"

[[deps.lib4ti2_jll]]
deps = ["Artifacts", "GLPK_jll", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "79116185def638e73ea3d88ca6c10e210a1dc183"
uuid = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"
version = "1.6.10+0"

[[deps.libblastrampoline_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850b90-86db-534c-a0d3-1478176c7d93"
version = "5.11.0+0"

[[deps.libsodium_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "011b0a7331b41c25524b64dc42afc9683ee89026"
uuid = "a9144af2-ca23-56d9-984f-0d03f7b5ccf8"
version = "1.0.21+0"

[[deps.nauty_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "c31f5c1b1d8ce050690a70b78ddb6e56bd0f6eda"
uuid = "55c6dc9b-343a-50ca-8ff2-b71adb3733d5"
version = "2.8.10+1"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"
version = "1.59.0+0"

[[deps.normaliz_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "FLINT_jll", "GMP_jll", "JLLWrappers", "LLVMOpenMP_jll", "Libdl", "MPFR_jll", "OpenBLAS32_jll", "nauty_jll"]
git-tree-sha1 = "4224940fe98b1d650e8c599c78e61c2aa01db0a9"
uuid = "6690c6e9-4e12-53b8-b8fd-4bffaef8839f"
version = "300.1001.503+0"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
version = "17.4.0+2"
